language: php

php:
    - 5.4
    - 5.3
    - 5.2

matrix:
  allow_failures:
    - php: 5.2

before_script:
    - ./travis/compile.sh
env:
    - REPORT_EXIT_STATUS=1

script: TEST_PHP_EXECUTABLE=`phpenv which php` php run-tests.php -g "FAIL,XFAIL,BORK,WARN,LEAK,SKIP"
